### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by jness** [iuscommunity/dmirr#3]
I noticed the Python memcache module is needed but not required by the setup.py:

   http://pypi.python.org/pypi/python-memcached

**Comment by derks** [comment]
memcached is only required if the memcached caching backend is used via settings.py, which it isn't in development/default config.

<pre>
CACHES['default'] = CACHES['dummy']
</pre>

**Comment by jness** [comment]
Running ./util/run.sh on a fresh pull returned a Python error for missing module 'memcache'
